name: Compilacion Manual Android 17
on:
  workflow_dispatch: # Esto nos permite activarlo con un boton a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ryfineZ/carrier-ims-for-pixel
        ref: refs/pull/61/head

    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permisos a Gradlew
      run: chmod +x gradlew

    - name: Compilar APK de depuracion
      run: ./gradlew assembleDebug

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: PixelIMS-Android17-Fix
        path: app/build/outputs/apk/debug/app-debug.apk
