name: Compilacion Manual Android 17
on:
  workflow_dispatch: # Activación manual por botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ryfineZ/carrier-ims-for-pixel
        ref: refs/pull/61/head

    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permisos a Gradlew
      run: chmod +x gradlew

    - name: Generar Keystore Dummy Autentico
      run: |
        keytool -genkeypair -v -keystore /tmp/dummy.jks -alias dummy_alias -keyalg RSA -keysize 2048 -validity 10000 -storepass dummy_password -keypass dummy_password -dname "CN=PixelIMS, O=Android, C=US"

    - name: Compilar con Gradle
      env:
        SIGN_KEY_STORE_FILE: "/tmp/dummy.jks"
        SIGN_KEY_STORE_PASSWORD: "dummy_password"
        SIGN_KEY_ALIAS: "dummy_alias"
        SIGN_KEY_PASSWORD: "dummy_password"
      run: ./gradlew assembleDebug

    - name: Subir APK Detectado
      uses: actions/upload-artifact@v4
      with:
        name: PixelIMS-Android17-Fix
        path: app/build/outputs/apk/debug/app-debug.apk
